version: '3.8'

services:
  # Mitmproxy 服务
  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy_service
    ports:
      - "8080:8080"  # 代理端口
    volumes:
      - ./mitmproxy_scripts:/home/mitmproxy/scripts:ro
      - ./mitmproxy_certs:/home/mitmproxy/.mitmproxy
      - ./shared_xhs_data:/home/mitmproxy/xhs_data
    working_dir: /home/mitmproxy
    command: >
      mitmdump
      -s /home/mitmproxy/scripts/xhs_interceptor.py
      --set listen_host=0.0.0.0
      --set block_global=false
      --set flow_detail=1
    restart: unless-stopped
    networks:
      - xhs_network

  # 数据上传服务
  uploader:
    build:
      context: ./uploader_service
      dockerfile: Dockerfile
    container_name: uploader_service
    volumes:
      - ./shared_xhs_data:/app/xhs_data
    restart: unless-stopped
    networks:
      - xhs_network

  # Firebase 监听器服务
  firebase_listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firebase_listener_service
    volumes:
      - ./firebase-service-account-key.json:/app/firebase-service-account-key.json:ro
      - ./config:/app/config:ro
      - ./docker.env:/app/.env:ro
      - ${MUMU_INSTALL_PATH}:/mumu:ro  # MuMu模拟器路径映射
    environment:
      - RUNNING_MODE=docker
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 允许容器访问宿主机
    ports:
      - "5037:5037"  # ADB端口映射
    restart: unless-stopped
    networks:
      - xhs_network

networks:
  xhs_network:
    driver: bridge