version: '3.8'

services:
  # Mitmproxy 服务
  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy_service
    ports:
      - "8085:8085"  # 代理端口
      - "8083:8083"  # web界面端口
    volumes:
      - ./mitmproxy_scripts:/home/mitmproxy/scripts:ro
      - ./mitmproxy_certs:/home/mitmproxy/.mitmproxy
      - ./shared_xhs_data:/home/mitmproxy/xhs_data
    working_dir: /home/mitmproxy
    command: >
      mitmweb
      -s /home/mitmproxy/scripts/xhs_interceptor.py
      --set listen_host=0.0.0.0
      --set block_global=false
      --set flow_detail=1
      -p 8085
      --web-port 8083
    restart: unless-stopped
    networks:
      - xhs_network

  # 数据上传服务
  uploader:
    build:
      context: ./uploader_service
      dockerfile: Dockerfile
    container_name: uploader_service
    volumes:
      - ./shared_xhs_data:/app/xhs_data
    restart: unless-stopped
    networks:
      - xhs_network

  # Firebase 监听器服务
  firebase_listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firebase_listener_service
    volumes:
      - ./firebase-service-account-key.json:/xiaohongshuZDH/firebase-service-account-key.json:ro
      - ./config:/xiaohongshuZDH/config:ro
      - ./docker.env:/xiaohongshuZDH/.env:ro
      - ./shared_data:/xiaohongshuZDH/shared_data:ro
      - ./shared:/app/shared
    environment:
      - RUNNING_MODE=docker
      - ADB_SERVER_HOST=host.docker.internal
      - ADB_SERVER_PORT=5037
      - ANDROID_ADB_SERVER_HOST=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - xhs_network

networks:
  xhs_network:
    driver: bridge