appium_servers:
  - id: "server_1"  # 给服务器起一个唯一的内部名字
    # url: "http://127.0.0.1:4723" # 您启动的第一个 Appium 服务器的 URL
    url: "http://appium_server1:4723"  # 使用Docker服务名称
    system_port: 8200            # 与 server1_caps.json 中定义的 systemPort 一致
    wda_local_port: 8100
    chromedriver_port: 9515      # 与 server1_caps.json 中定义的 chromedriverPort 一致
    intended_emulator_id: "127.0.0.1:16384" 

  - id: "server_2"
    # url: "http://127.0.0.1:4725" # 您启动的第二个 Appium 服务器的 URL
    url: "http://appium_server2:4725"  # 使用Docker服务名称
    system_port: 8201            # 与 server2_caps.json 中定义的 systemPort 一致
    wda_local_port: 8101
    chromedriver_port: 9516      # 与 server2_caps.json 中定义的 chromedriverPort 一致
    intended_emulator_id: "127.0.0.1:16448"

  # - id: "server_3"
  #   url: "http://127.0.0.1:4727" # 您启动的第三个 Appium 服务器的 URL
  #   system_port: 8202            # 与 server3_caps.json 中定义的 systemPort 一致
  #   chromedriver_port: 9517      # 与 server3_caps.json 中定义的 chromedriverPort 一致
    # intended_emulator_id: "emulator-5558" # 可选

  # 根据您实际启动的 Appium 服务器数量和配置继续添加...